packages:
  - 'client'
  - 'server'
  - 'packages/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - argon2
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
