import type { Prisma } from '@prisma/client'

export type SeedUserStatus = 'ACTIVE' | 'PENDING_VERIFICATION' | 'SUSPENDED'
export type SeedStoreStatus =
    | 'APPROVED'
    | 'SUBMITTED'
    | 'UNDER_REVIEW'
    | 'REJECTED'
    | 'SUSPENDED'
export type SeedProductStatus = 'ACTIVE' | 'DRAFT' | 'ARCHIVED'
export type SeedTemplate = 'DEFAULT' | 'VIBRANT_MARKET' | 'ISHUSHO_CRAFTS'

export type CatalogPerson = {
    phoneNumber: string
    fullName: string
    email: string
    status?: SeedUserStatus
    createdDaysAgo: number
}

export type CatalogStore = {
    owner: CatalogPerson
    slug: string
    status: SeedStoreStatus
    registeredName: string
    displayName: string
    description: string
    aboutUs: string
    contactAddress: string
    industryCode: string
    categoryCode: string
    country: string
    ownerNationality: string
    address: {
        province: string
        district: string
        sector: string
        physicalAddress: string
        googleMapsUrl: string
    }
    ratingAvg: number
    ratingCount: number
    approvedDaysAgo?: number
    createdDaysAgo: number
    rejectionReason?: string | null
    brandColors: { primary: string; secondary: string; template: SeedTemplate }
}

export type CatalogVariant = {
    sku: string
    title: string
    colorName?: string | null
    colorHex?: string | null
    size?: string | null
    model?: string | null
    price: number
    cost: number
    stock: number
    reserved?: number
    attributes?: Prisma.InputJsonValue
}

export type CatalogProduct = {
    storeSlug: string
    name: string
    description: string
    vendor: string
    category: string
    categorySlug: string
    status: SeedProductStatus
    tags: string[]
    attributes: Prisma.InputJsonValue
    deliveryPrice: number
    deliveryLocation: string
    createdDaysAgo: number
    variants: CatalogVariant[]
    imageViews?: string[]
}

export function kebab(value: string): string {
    return value
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
}

const DJ = 'https://cdn.dummyjson.com/product-images'

function unsplash(id: string): string {
    return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`
}

function dummy(path: string, count = 1): string[] {
    return Array.from({ length: count }, (_, index) => `${DJ}/${path}/${index + 1}.webp`)
}

function picsum(seed: string): string {
    return `https://picsum.photos/seed/${encodeURIComponent(seed)}/900/1100`
}

/** Real catalog photos keyed by product name. DummyJSON first, then FakeStore / Unsplash. */
export const PRODUCT_PHOTOS: Record<string, string[]> = {
    'Sunrise Coffee Beans': [
        `${DJ}/groceries/nescafe-coffee/1.webp`,
        unsplash('photo-1447933601403-0c6688de566e'),
        unsplash('photo-1495474472287-4d71bcdd2085'),
    ],
    'River Valley Rice': [
        `${DJ}/groceries/rice/1.webp`,
        unsplash('photo-1536304993881-ff6e9eefa2a6'),
        unsplash('photo-1516684669134-de6f7c473a2a'),
    ],
    'Seasonal Spice Mix': [
        unsplash('photo-1596040033229-a9821ebd058d'),
        unsplash('photo-1506368249639-73a05d6f6488'),
        `${DJ}/groceries/green-chili-pepper/1.webp`,
    ],
    'Harbor Wireless Headphones': [
        `${DJ}/mobile-accessories/apple-airpods-max-silver/1.webp`,
        ...dummy('mobile-accessories/apple-airpods', 3),
    ],
    'Compact Wall Charger': dummy('mobile-accessories/apple-iphone-charger', 2).concat(
        `${DJ}/mobile-accessories/apple-airpower-wireless-charger/1.webp`,
    ),
    'Legacy Feature Phone': dummy('smartphones/iphone-5s', 3),
    'Coastal Cotton Tee': dummy('mens-shirts/gigabyte-aorus-men-tshirt', 4).slice(0, 3),
    'Fold Leather Wallet': [
        unsplash('photo-1627123424574-724758594e93'),
        unsplash('photo-1618354691373-d851c5c3a990'),
        unsplash('photo-1606503153255-59d8b8b82176'),
    ],
    'Highland Honey': [
        `${DJ}/groceries/honey-jar/1.webp`,
        unsplash('photo-1587049352846-4a222e784d38'),
        unsplash('photo-1558642452-9d2a7deb7f62'),
    ],
    'Red Palm Oil': [
        `${DJ}/groceries/cooking-oil/1.webp`,
        unsplash('photo-1474979266404-7eaacbcd87c5'),
        unsplash('photo-1508747703725-719777637510'),
    ],
    'Plantain Chips': [
        unsplash('photo-1571771894821-ce9b6c11b08e'),
        unsplash('photo-1566478989037-eec170784d0b'),
        unsplash('photo-1613919113640-25732ec5e61f'),
    ],
    'Dried Hibiscus': [
        unsplash('photo-1597318181409-cf64d0b5d8a2'),
        unsplash('photo-1576092768241-dec231879fc3'),
        `${DJ}/groceries/juice/1.webp`,
    ],
    'Harbor Bluetooth Speaker': [
        ...dummy('mobile-accessories/amazon-echo-plus', 2),
        `${DJ}/mobile-accessories/apple-homepod-mini-cosmic-grey/1.webp`,
    ],
    'Power Bank 20000mAh': dummy('mobile-accessories/apple-magsafe-battery-pack', 2).concat(
        unsplash('photo-1609091839311-d5365f9ff1c5'),
    ),
    'Quiet Wireless Mouse': [
        unsplash('photo-1527864550417-7fd91fc51a46'),
        unsplash('photo-1615663245857-ac93bb7c39e7'),
        unsplash('photo-1593640408182-31c70c8268f5'),
    ],
    'Glass Screen Protector Pack': dummy(
        'mobile-accessories/iphone-12-silicone-case-with-magsafe-plum',
        3,
    ),
    'Linen Shirt Dress': dummy('tops/gray-dress', 3),
    'Canvas Slip-Ons': dummy('mens-shoes/puma-future-rider-trainers', 3),
    'Wax Print Scarf': [
        unsplash('photo-1601924994987-69e26d50dc26'),
        unsplash('photo-1520903920243-00d872a2d1c9'),
        unsplash('photo-1591047139829-d91aecb6caea'),
    ],
    'Immune Vitamin C Tablets': [
        unsplash('photo-1587854692152-cbe660dbde88'),
        unsplash('photo-1576092768241-dec231879fc3'),
        unsplash('photo-1550572017-edd951aa5514'),
    ],
    'Herbal Cough Syrup': [
        unsplash('photo-1631549916768-4119b2e5f926'),
        unsplash('photo-1587854692152-cbe660dbde88'),
        `${DJ}/groceries/honey-jar/1.webp`,
    ],
    'Acacia Side Table': dummy('furniture/bedside-table-african-cherry', 3),
    'Woven Floor Cushion': [
        unsplash('photo-1555041469-a586c61ea9bc'),
        unsplash('photo-1584100936595-c0654b55a2e2'),
        unsplash('photo-1493663284031-b7e3aefcae8e'),
    ],
    'Shea Body Butter': dummy('skin-care/olay-ultra-moisture-shea-butter-body-wash', 3),
    'Hibiscus Hair Oil': dummy('fragrances/calvin-klein-ck-one', 3),
    'Trail Running Shoes': dummy('mens-shoes/nike-air-jordan-1-red-and-black', 3),
    'Resistance Band Set': [
        unsplash('photo-1598289431512-b97b0917affc'),
        unsplash('photo-1517836357463-d25dfeac3438'),
        unsplash('photo-1571019614242-c5c5dee9f50b'),
    ],
    'Wooden Puzzle Set': [
        unsplash('photo-1587654780291-39c9404d746b'),
        unsplash('photo-1566576912321-d58ddd7a6088'),
        unsplash('photo-1515488042361-ee00e0ddd4e4'),
    ],
    'Soft Cotton Onesie': [
        unsplash('photo-1522771930-78848d9293e8'),
        unsplash('photo-1515488042361-ee00e0ddd4e4'),
        ...dummy('tops/girl-summer-dress', 1),
    ],
    'Akabanga Chili Oil': [
        `${DJ}/groceries/green-chili-pepper/1.webp`,
        `${DJ}/groceries/cooking-oil/1.webp`,
        unsplash('photo-1506806732259-39c2d0268443'),
    ],
    'Banana Wine': [
        unsplash('photo-1510812431401-41d2bd2722f3'),
        unsplash('photo-1553361371-9b22f78e8b1d'),
        unsplash('photo-1506377247377-2a5b3b417ebb'),
    ],
    'Compact Laptop Stand': dummy('laptops/apple-macbook-pro-14-inch-space-grey', 3),
    'USB-C Hub 7-in-1': [
        unsplash('photo-1587825140708-dfaf72ae4b04'),
        unsplash('photo-1593640408182-31c70c8268f5'),
        unsplash('photo-1519389950473-47ba0277781c'),
    ],
    'Kitenge Tote Bag': dummy("womens-bags/blue-women's-handbag", 3),
    'Beaded Bracelet Set': dummy('womens-jewellery/tropical-earring', 3),
    'Digital Thermometer': [
        unsplash('photo-1576092768241-dec231879fc3'),
        unsplash('photo-1587854692152-cbe660dbde88'),
        unsplash('photo-1530497610245-94d3c16cda28'),
    ],
    'First Aid Pouch': [
        unsplash('photo-1603398938378-e54eab446dde'),
        unsplash('photo-1576092768241-dec231879fc3'),
        unsplash('photo-1631815588090-d4bfec5b1ccb'),
    ],
    'Jollof Spice Kit': [
        unsplash('photo-1596040033229-a9821ebd058d'),
        unsplash('photo-1596040033229-c51285735049'),
        `${DJ}/groceries/green-chili-pepper/1.webp`,
    ],
    'Smoked Pepper Mix': [
        `${DJ}/groceries/green-bell-pepper/1.webp`,
        `${DJ}/groceries/green-chili-pepper/1.webp`,
        unsplash('photo-1506806732259-39c2d0268443'),
    ],
    'Clay Table Vase': dummy('home-decoration/plant-pot', 3),
    'Handwoven Table Runner': [
        unsplash('photo-1600585152220-90363fe7e115'),
        unsplash('photo-1618221195710-dd6b41faaea6'),
        unsplash('photo-1555041469-a586c61ea9bc'),
    ],
    'Adjustable Jump Rope': [
        unsplash('photo-1517836357463-d25dfeac3438'),
        unsplash('photo-1571019614242-c5c5dee9f50b'),
        unsplash('photo-1534438327276-14e5300c3a48'),
    ],
    'Yoga Block Pair': [
        unsplash('photo-1544367567-0f2fcb009e0b'),
        unsplash('photo-1506126613408-eca07ce68773'),
        unsplash('photo-1545389336-cf090694435e'),
    ],
    'Premium Cotton T-Shirt': dummy('mens-shirts/man-short-sleeve-shirt', 3),
    'Wireless Bluetooth Headphones': [
        `${DJ}/mobile-accessories/beats-flex-wireless-earphones/1.webp`,
        ...dummy('mobile-accessories/apple-airpods', 2),
    ],
    'Organic Coffee Beans': [
        `${DJ}/groceries/nescafe-coffee/1.webp`,
        unsplash('photo-1447933601403-0c6688de566e'),
        unsplash('photo-1559056199-641a0ac8b55e'),
    ],
    'Leather Wallet': [
        unsplash('photo-1627123424574-724758594e93'),
        unsplash('photo-1618354691373-d851c5c3a990'),
    ],
    'Yoga Mat Pro': [
        unsplash('photo-1544367567-0f2fcb009e0b'),
        unsplash('photo-1601925260368-ae2f83cf8b7f'),
        unsplash('photo-1518611012118-696072aa579a'),
    ],
}

const PRODUCT_PHOTO_HINTS: Array<{ keys: string[]; urls: string[] }> = [
    { keys: ['coffee', 'bean', 'nescafe'], urls: PRODUCT_PHOTOS['Sunrise Coffee Beans'] },
    { keys: ['rice'], urls: PRODUCT_PHOTOS['River Valley Rice'] },
    { keys: ['honey'], urls: PRODUCT_PHOTOS['Highland Honey'] },
    { keys: ['oil', 'palm'], urls: PRODUCT_PHOTOS['Red Palm Oil'] },
    { keys: ['chip', 'plantain'], urls: PRODUCT_PHOTOS['Plantain Chips'] },
    { keys: ['hibiscus', 'tea'], urls: PRODUCT_PHOTOS['Dried Hibiscus'] },
    { keys: ['headphone', 'airpod', 'earphone'], urls: PRODUCT_PHOTOS['Harbor Wireless Headphones'] },
    { keys: ['charger'], urls: PRODUCT_PHOTOS['Compact Wall Charger'] },
    { keys: ['phone', 'iphone'], urls: PRODUCT_PHOTOS['Legacy Feature Phone'] },
    { keys: ['tee', 'tshirt', 't-shirt', 'shirt'], urls: PRODUCT_PHOTOS['Coastal Cotton Tee'] },
    { keys: ['wallet', 'leather'], urls: PRODUCT_PHOTOS['Fold Leather Wallet'] },
    { keys: ['speaker', 'echo', 'homepod'], urls: PRODUCT_PHOTOS['Harbor Bluetooth Speaker'] },
    { keys: ['power', 'battery', 'bank'], urls: PRODUCT_PHOTOS['Power Bank 20000mAh'] },
    { keys: ['mouse'], urls: PRODUCT_PHOTOS['Quiet Wireless Mouse'] },
    { keys: ['screen', 'glass', 'case'], urls: PRODUCT_PHOTOS['Glass Screen Protector Pack'] },
    { keys: ['dress'], urls: PRODUCT_PHOTOS['Linen Shirt Dress'] },
    { keys: ['slip', 'shoe', 'sneaker', 'trainer'], urls: PRODUCT_PHOTOS['Trail Running Shoes'] },
    { keys: ['scarf'], urls: PRODUCT_PHOTOS['Wax Print Scarf'] },
    { keys: ['vitamin', 'tablet'], urls: PRODUCT_PHOTOS['Immune Vitamin C Tablets'] },
    { keys: ['syrup'], urls: PRODUCT_PHOTOS['Herbal Cough Syrup'] },
    { keys: ['table', 'furniture'], urls: PRODUCT_PHOTOS['Acacia Side Table'] },
    { keys: ['cushion'], urls: PRODUCT_PHOTOS['Woven Floor Cushion'] },
    { keys: ['shea', 'butter', 'body'], urls: PRODUCT_PHOTOS['Shea Body Butter'] },
    { keys: ['hair'], urls: PRODUCT_PHOTOS['Hibiscus Hair Oil'] },
    { keys: ['band', 'resistance'], urls: PRODUCT_PHOTOS['Resistance Band Set'] },
    { keys: ['puzzle', 'toy', 'wooden'], urls: PRODUCT_PHOTOS['Wooden Puzzle Set'] },
    { keys: ['onesie', 'baby'], urls: PRODUCT_PHOTOS['Soft Cotton Onesie'] },
    { keys: ['chili', 'akabanga', 'pepper'], urls: PRODUCT_PHOTOS['Akabanga Chili Oil'] },
    { keys: ['wine'], urls: PRODUCT_PHOTOS['Banana Wine'] },
    { keys: ['laptop', 'stand', 'macbook'], urls: PRODUCT_PHOTOS['Compact Laptop Stand'] },
    { keys: ['hub', 'usb'], urls: PRODUCT_PHOTOS['USB-C Hub 7-in-1'] },
    { keys: ['tote', 'bag', 'handbag'], urls: PRODUCT_PHOTOS['Kitenge Tote Bag'] },
    { keys: ['bracelet', 'bead', 'jewel'], urls: PRODUCT_PHOTOS['Beaded Bracelet Set'] },
    { keys: ['thermo'], urls: PRODUCT_PHOTOS['Digital Thermometer'] },
    { keys: ['aid', 'first'], urls: PRODUCT_PHOTOS['First Aid Pouch'] },
    { keys: ['spice', 'jollof'], urls: PRODUCT_PHOTOS['Jollof Spice Kit'] },
    { keys: ['vase', 'pot', 'clay'], urls: PRODUCT_PHOTOS['Clay Table Vase'] },
    { keys: ['runner'], urls: PRODUCT_PHOTOS['Handwoven Table Runner'] },
    { keys: ['rope', 'jump'], urls: PRODUCT_PHOTOS['Adjustable Jump Rope'] },
    { keys: ['yoga', 'block', 'mat'], urls: PRODUCT_PHOTOS['Yoga Block Pair'] },
]

export const STORE_PHOTOS: Record<string, string> = {
    'harvest-market': unsplash('photo-1542838132-92c53300491e'),
    'northline-electronics': unsplash('photo-1519389950473-47ba0277781c'),
    'atelier-threads': unsplash('photo-1441986300917-64674bd600d8'),
    'pending-goods': unsplash('photo-1472851294608-062f824d29cc'),
    'review-house': unsplash('photo-1556740749-887f6717d7e4'),
    'closed-corner': unsplash('photo-1528698827591-e19ccd7bc23d'),
    'paused-mart': unsplash('photo-1488459716781-31db52582fe9'),
    'lakeview-pharmacy': unsplash('photo-1586015555751-63bb77f4322a'),
    'savanna-home': unsplash('photo-1555041469-a586c61ea9bc'),
    'bloom-beauty': unsplash('photo-1596462502278-27bfdc403348'),
    'peak-athletics': unsplash('photo-1534438327276-14e5300c3a48'),
    'little-baobab': unsplash('photo-1515488042361-ee00e0ddd4e4'),
    'kigali-pantry': unsplash('photo-1488459716781-31db52582fe9'),
    'volta-gadgets': unsplash('photo-1498049794561-7780e7231661'),
    'umuco-atelier': unsplash('photo-1445205170230-053b83016050'),
    'cedar-wellness': unsplash('photo-1576092768241-dec231879fc3'),
    'jollof-kitchen': unsplash('photo-1556910103-1c02745aae4d'),
    'acacia-living': unsplash('photo-1618221195710-dd6b41faaea6'),
    'nile-sports': unsplash('photo-1571902943202-507ec2618e8f'),
    'demo-kigali': unsplash('photo-1488459716781-31db52582fe9'),
    'coastal-staples': unsplash('photo-1578916171728-46686eac8d58'),
    'sahel-threads': unsplash('photo-1441984904996-e0b6ba687e04'),
    'inkuru-books': unsplash('photo-1512820790803-83ca734da794'),
    'harbor-spares': unsplash('photo-1486262715619-67b85e0b08d3'),
    'oasis-spa-shop': unsplash('photo-1544161515-4ab6ce6db874'),
    'ridge-hardware': unsplash('photo-1504328345606-18bbc8c9d7d1'),
    'gold-coast-audio': unsplash('photo-1505740420928-5e560c06d30e'),
    'intore-fitness': unsplash('photo-1534438327276-14e5300c3a48'),
    'red-earth-goods': unsplash('photo-1604719312566-8912e9227c6a'),
    'faded-linen': unsplash('photo-1558171813-4c088753af8f'),
    'broken-circuit': unsplash('photo-1511707171634-5f897ff02aa9'),
    'dry-season-mart': unsplash('photo-1542838132-92c53300491e'),
    'quiet-aisle': unsplash('photo-1578916171728-46686eac8d58'),
    'paused-pixels': unsplash('photo-1519389950473-47ba0277781c'),
    'held-hanger': unsplash('photo-1441986300917-64674bd600d8'),
    'frozen-aisle': unsplash('photo-1578916171728-46686eac8d58'),
}

const RECEIPT_PHOTOS = [
    unsplash('photo-1554224155-6726b3ff858f'),
    unsplash('photo-1556742049-0cfed4f6a45d'),
    unsplash('photo-1563013544-824ae1b704d3'),
]

export function resolveProductPhotos(query: string): string[] {
    const exact = PRODUCT_PHOTOS[query]
    if (exact?.length) return exact
    const hay = query.toLowerCase().replace(/[-_/]+/g, ' ')
    for (const hint of PRODUCT_PHOTO_HINTS) {
        if (hint.keys.some((key) => hay.includes(key))) return hint.urls
    }
    return [picsum(kebab(query) || 'product')]
}

export function productImages(name: string, _views = ['front', 'angle', 'detail']): string[] {
    return resolveProductPhotos(name)
}

export function variantImage(sku: string): string {
    const photos = resolveProductPhotos(sku)
    return photos[0] ?? picsum(sku)
}

export function storeLogoUrl(slug: string, _primaryHex?: string): string {
    return STORE_PHOTOS[slug] ?? unsplash('photo-1441986300917-64674bd600d8')
}

export function paymentProofUrl(orderNumber: string): string {
    const index = Math.abs(orderNumber.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0))
    return RECEIPT_PHOTOS[index % RECEIPT_PHOTOS.length]
}

export const EXTRA_DELIVERY_ZONES = [
    { name: 'City center', feeRwf: 1500, etaMinutes: 45 },
    { name: 'Outer districts', feeRwf: 2500, etaMinutes: 90 },
    { name: 'Airport corridor', feeRwf: 3000, etaMinutes: 60 },
    { name: 'Lakeside towns', feeRwf: 4000, etaMinutes: 150 },
    { name: 'Same-day express', feeRwf: 5000, etaMinutes: 30 },
] as const

export const EXTRA_CUSTOMERS: CatalogPerson[] = [
    { phoneNumber: '+233200000110', fullName: 'Kofi Asante', email: 'kofi.asante@onlineshop.rw', createdDaysAgo: 58 },
    { phoneNumber: '+233200000111', fullName: 'Abena Serwaa', email: 'abena.serwaa@onlineshop.rw', createdDaysAgo: 54 },
    { phoneNumber: '+233200000112', fullName: 'Nia Kabasele', email: 'nia.kabasele@onlineshop.rw', createdDaysAgo: 51 },
    { phoneNumber: '+233200000113', fullName: 'Tariq Osei', email: 'tariq.osei@onlineshop.rw', createdDaysAgo: 48 },
    { phoneNumber: '+233200000114', fullName: 'Zainab Traore', email: 'zainab.traore@onlineshop.rw', createdDaysAgo: 46 },
    { phoneNumber: '+233200000115', fullName: 'Jean-Paul Habimana', email: 'jeanpaul.habimana@onlineshop.rw', createdDaysAgo: 44 },
    { phoneNumber: '+233200000116', fullName: 'Wanjiku Njeri', email: 'wanjiku.njeri@onlineshop.rw', createdDaysAgo: 41 },
    { phoneNumber: '+233200000117', fullName: 'Omar Diop', email: 'omar.diop@onlineshop.rw', createdDaysAgo: 38 },
    { phoneNumber: '+233200000118', fullName: 'Thandiwe Ncube', email: 'thandiwe.ncube@onlineshop.rw', createdDaysAgo: 36 },
    { phoneNumber: '+233200000119', fullName: 'Kwesi Boateng', email: 'kwesi.boateng@onlineshop.rw', createdDaysAgo: 33 },
    { phoneNumber: '+233200000120', fullName: 'Amina Uwase', email: 'amina.uwase@onlineshop.rw', createdDaysAgo: 31 },
    { phoneNumber: '+233200000121', fullName: 'David Okello', email: 'david.okello@onlineshop.rw', createdDaysAgo: 28 },
    { phoneNumber: '+233200000122', fullName: 'Fatima Keita', email: 'fatima.keita@onlineshop.rw', createdDaysAgo: 26 },
    { phoneNumber: '+233200000123', fullName: 'Ibrahim Suleiman', email: 'ibrahim.suleiman@onlineshop.rw', createdDaysAgo: 23 },
    { phoneNumber: '+233200000124', fullName: 'Chiamaka Obi', email: 'chiamaka.obi@onlineshop.rw', createdDaysAgo: 21 },
    { phoneNumber: '+233200000125', fullName: 'Lamine Fall', email: 'lamine.fall@onlineshop.rw', createdDaysAgo: 18 },
    { phoneNumber: '+233200000126', fullName: 'Grace Mukamana', email: 'grace.mukamana@onlineshop.rw', createdDaysAgo: 15 },
    { phoneNumber: '+233200000127', fullName: 'Elias Tesfaye', email: 'elias.tesfaye@onlineshop.rw', createdDaysAgo: 12 },
    { phoneNumber: '+233200000128', fullName: 'Nadia Bensouda', email: 'nadia.bensouda@onlineshop.rw', status: 'PENDING_VERIFICATION', createdDaysAgo: 4 },
    { phoneNumber: '+233200000129', fullName: 'Patrick Mugisha', email: 'patrick.mugisha@onlineshop.rw', status: 'SUSPENDED', createdDaysAgo: 19 },
]

export const DRAFT_ONLY_OWNERS: CatalogPerson[] = [
    {
        phoneNumber: '+233200000060',
        fullName: 'Ruth Acheampong',
        email: 'ruth.acheampong@onlineshop.rw',
        createdDaysAgo: 6,
    },
    {
        phoneNumber: '+233200000061',
        fullName: 'Musa Jallow',
        email: 'musa.jallow@onlineshop.rw',
        createdDaysAgo: 3,
    },
]

export const EXTRA_APPROVED_STORES: CatalogStore[] = [
    {
        owner: { phoneNumber: '+233200000020', fullName: 'Efua Mensima', email: 'efua@onlineshop.rw', createdDaysAgo: 72 },
        slug: 'lakeview-pharmacy',
        status: 'APPROVED',
        registeredName: 'Lakeview Pharmacy Ltd',
        displayName: 'Lakeview Pharmacy',
        description: 'Everyday medicines, vitamins, and first-aid supplies with pharmacist advice.',
        aboutUs: 'Lakeview started as a neighborhood counter in Kisumu and now ships sealed health products across the marketplace.',
        contactAddress: 'Lake Road, Kisumu',
        industryCode: 'HEALTHCARE',
        categoryCode: 'PHARMACY',
        country: 'KE',
        ownerNationality: 'Kenyan',
        address: {
            province: 'Kisumu',
            district: 'Kisumu Central',
            sector: 'Milimani',
            physicalAddress: '14 Lake Road',
            googleMapsUrl: 'https://maps.google.com/?q=14+Lake+Road+Kisumu',
        },
        ratingAvg: 4.7,
        ratingCount: 6,
        approvedDaysAgo: 68,
        createdDaysAgo: 71,
        brandColors: { primary: '#0f766e', secondary: '#042f2e', template: 'DEFAULT' },
    },
    {
        owner: { phoneNumber: '+233200000021', fullName: 'Benedictine Uwera', email: 'benedictine@onlineshop.rw', createdDaysAgo: 66 },
        slug: 'savanna-home',
        status: 'APPROVED',
        registeredName: 'Savanna Home Ltd',
        displayName: 'Savanna Home',
        description: 'Solid-wood furniture and textiles made for compact city apartments.',
        aboutUs: 'We work with carpenters in Huye and finish every piece before it leaves the workshop.',
        contactAddress: 'Ngoma, Huye',
        industryCode: 'HOME_LIVING',
        categoryCode: 'FURNITURE_STORE',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Southern',
            district: 'Huye',
            sector: 'Ngoma',
            physicalAddress: '8 Workshop Lane',
            googleMapsUrl: 'https://maps.google.com/?q=Ngoma+Huye+Rwanda',
        },
        ratingAvg: 4.5,
        ratingCount: 4,
        approvedDaysAgo: 60,
        createdDaysAgo: 64,
        brandColors: { primary: '#b45309', secondary: '#431407', template: 'ISHUSHO_CRAFTS' },
    },
    {
        owner: { phoneNumber: '+233200000022', fullName: 'Mariam Cisse', email: 'mariam.cisse@onlineshop.rw', createdDaysAgo: 63 },
        slug: 'bloom-beauty',
        status: 'APPROVED',
        registeredName: 'Bloom Beauty Ltd',
        displayName: 'Bloom Beauty',
        description: 'Shea, hibiscus, and botanical care mixed in small batches.',
        aboutUs: 'Bloom bottles what we already used at home: dense butters, light oils, and no filler fragrance.',
        contactAddress: 'Plateau, Abidjan',
        industryCode: 'BEAUTY_PERSONAL_CARE',
        categoryCode: 'COSMETICS_STORE',
        country: 'CI',
        ownerNationality: 'Ivorian',
        address: {
            province: 'Abidjan',
            district: 'Plateau',
            sector: 'Commerce',
            physicalAddress: '22 Rue des Jardins',
            googleMapsUrl: 'https://maps.google.com/?q=Plateau+Abidjan',
        },
        ratingAvg: 4.9,
        ratingCount: 8,
        approvedDaysAgo: 58,
        createdDaysAgo: 62,
        brandColors: { primary: '#be185d', secondary: '#500724', template: 'VIBRANT_MARKET' },
    },
    {
        owner: { phoneNumber: '+233200000023', fullName: 'Daniel Kariuki', email: 'daniel.kariuki@onlineshop.rw', createdDaysAgo: 59 },
        slug: 'peak-athletics',
        status: 'APPROVED',
        registeredName: 'Peak Athletics Ltd',
        displayName: 'Peak Athletics',
        description: 'Running shoes, bands, and training gear for warm-weather miles.',
        aboutUs: 'Peak is a running club that started selling the gear we could not find locally.',
        contactAddress: 'Westlands, Nairobi',
        industryCode: 'SPORTS_FITNESS',
        categoryCode: 'SPORTS_EQUIPMENT',
        country: 'KE',
        ownerNationality: 'Kenyan',
        address: {
            province: 'Nairobi',
            district: 'Westlands',
            sector: 'Parklands',
            physicalAddress: '5 Ring Trail Court',
            googleMapsUrl: 'https://maps.google.com/?q=Westlands+Nairobi',
        },
        ratingAvg: 4.3,
        ratingCount: 5,
        approvedDaysAgo: 54,
        createdDaysAgo: 58,
        brandColors: { primary: '#ea580c', secondary: '#7c2d12', template: 'VIBRANT_MARKET' },
    },
    {
        owner: { phoneNumber: '+233200000024', fullName: 'Ayo Adewale', email: 'ayo.adewale@onlineshop.rw', createdDaysAgo: 57 },
        slug: 'little-baobab',
        status: 'APPROVED',
        registeredName: 'Little Baobab Ltd',
        displayName: 'Little Baobab',
        description: 'Wooden toys and soft cotton basics for small children.',
        aboutUs: 'Every toy is sanded by hand and every onesie is pre-washed before it is listed.',
        contactAddress: 'Ikeja, Lagos',
        industryCode: 'RETAIL',
        categoryCode: 'SPECIALTY_STORE',
        country: 'NG',
        ownerNationality: 'Nigerian',
        address: {
            province: 'Lagos',
            district: 'Ikeja',
            sector: 'Allen',
            physicalAddress: '19 Baobab Close',
            googleMapsUrl: 'https://maps.google.com/?q=Ikeja+Lagos',
        },
        ratingAvg: 4.6,
        ratingCount: 3,
        approvedDaysAgo: 52,
        createdDaysAgo: 56,
        brandColors: { primary: '#ca8a04', secondary: '#422006', template: 'ISHUSHO_CRAFTS' },
    },
    {
        owner: { phoneNumber: '+233200000025', fullName: 'Claudine Mukeshimana', email: 'claudine@onlineshop.rw', createdDaysAgo: 55 },
        slug: 'kigali-pantry',
        status: 'APPROVED',
        registeredName: 'Kigali Pantry Ltd',
        displayName: 'Kigali Pantry',
        description: 'Chili oil, banana wine, and packed condiments from Kigali kitchens.',
        aboutUs: 'We bottle what families already cook with, then label it for the marketplace.',
        contactAddress: 'Kimironko, Kigali',
        industryCode: 'FOOD_BEVERAGE',
        categoryCode: 'FOOD_PROCESSING',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Kigali',
            district: 'Gasabo',
            sector: 'Kimironko',
            physicalAddress: 'KG 11 Ave, stall 4',
            googleMapsUrl: 'https://maps.google.com/?q=Kimironko+Market+Kigali',
        },
        ratingAvg: 4.4,
        ratingCount: 7,
        approvedDaysAgo: 50,
        createdDaysAgo: 54,
        brandColors: { primary: '#b91c1c', secondary: '#450a0a', template: 'VIBRANT_MARKET' },
    },
    {
        owner: { phoneNumber: '+233200000026', fullName: 'Nana Yeboah', email: 'nana.yeboah@onlineshop.rw', createdDaysAgo: 52 },
        slug: 'volta-gadgets',
        status: 'APPROVED',
        registeredName: 'Volta Gadgets Ltd',
        displayName: 'Volta Gadgets',
        description: 'Laptop stands, hubs, and desk accessories with local pickup.',
        aboutUs: 'Volta tests every cable on a live machine before it is bagged.',
        contactAddress: 'East Legon, Accra',
        industryCode: 'ELECTRONICS_TECH',
        categoryCode: 'COMPUTER_STORE',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Greater Accra',
            district: 'Accra Metro',
            sector: 'East Legon',
            physicalAddress: '31 Boundary Road',
            googleMapsUrl: 'https://maps.google.com/?q=East+Legon+Accra',
        },
        ratingAvg: 4.2,
        ratingCount: 4,
        approvedDaysAgo: 47,
        createdDaysAgo: 51,
        brandColors: { primary: '#4f46e5', secondary: '#1e1b4b', template: 'DEFAULT' },
    },
    {
        owner: { phoneNumber: '+233200000027', fullName: 'Keza Ingabire', email: 'keza@onlineshop.rw', createdDaysAgo: 49 },
        slug: 'umuco-atelier',
        status: 'APPROVED',
        registeredName: 'Umuco Atelier Ltd',
        displayName: 'Umuco Atelier',
        description: 'Kitenge totes, beads, and accessories cut in Nyamirambo.',
        aboutUs: 'Umuco keeps offcuts in the shop and turns them into bags the same week.',
        contactAddress: 'Nyamirambo, Kigali',
        industryCode: 'FASHION_APPAREL',
        categoryCode: 'ACCESSORIES',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Kigali',
            district: 'Nyarugenge',
            sector: 'Nyamirambo',
            physicalAddress: 'KN 2 Ave, house 18',
            googleMapsUrl: 'https://maps.google.com/?q=Nyamirambo+Kigali',
        },
        ratingAvg: 4.8,
        ratingCount: 9,
        approvedDaysAgo: 44,
        createdDaysAgo: 48,
        brandColors: { primary: '#7c3aed', secondary: '#2e1065', template: 'ISHUSHO_CRAFTS' },
    },
    {
        owner: { phoneNumber: '+233200000028', fullName: 'Sonia Appiah', email: 'sonia.appiah@onlineshop.rw', createdDaysAgo: 46 },
        slug: 'cedar-wellness',
        status: 'APPROVED',
        registeredName: 'Cedar Wellness Ltd',
        displayName: 'Cedar Wellness',
        description: 'Thermometers, pouches, and clinic-ready home kits.',
        aboutUs: 'Cedar packs kits the way a nurse would: labeled, sealed, and dated.',
        contactAddress: 'Cantonments, Accra',
        industryCode: 'HEALTHCARE',
        categoryCode: 'MEDICAL_SUPPLIES',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Greater Accra',
            district: 'Accra Metro',
            sector: 'Cantonments',
            physicalAddress: '6 Cedar Close',
            googleMapsUrl: 'https://maps.google.com/?q=Cantonments+Accra',
        },
        ratingAvg: 4.1,
        ratingCount: 3,
        approvedDaysAgo: 41,
        createdDaysAgo: 45,
        brandColors: { primary: '#0369a1', secondary: '#082f49', template: 'DEFAULT' },
    },
    {
        owner: { phoneNumber: '+233200000029', fullName: 'Folake Balogun', email: 'folake@onlineshop.rw', createdDaysAgo: 43 },
        slug: 'jollof-kitchen',
        status: 'APPROVED',
        registeredName: 'Jollof Kitchen Ltd',
        displayName: 'Jollof Kitchen',
        description: 'Spice kits and smoked pepper mixes for weekend pots.',
        aboutUs: 'We toast spices the morning they ship so the kit still smells like the pot.',
        contactAddress: 'Yaba, Lagos',
        industryCode: 'FOOD_BEVERAGE',
        categoryCode: 'RESTAURANT',
        country: 'NG',
        ownerNationality: 'Nigerian',
        address: {
            province: 'Lagos',
            district: 'Lagos Mainland',
            sector: 'Yaba',
            physicalAddress: '44 Herbert Macaulay',
            googleMapsUrl: 'https://maps.google.com/?q=Yaba+Lagos',
        },
        ratingAvg: 4.7,
        ratingCount: 11,
        approvedDaysAgo: 39,
        createdDaysAgo: 42,
        brandColors: { primary: '#c2410c', secondary: '#431407', template: 'VIBRANT_MARKET' },
    },
    {
        owner: { phoneNumber: '+233200000030', fullName: 'Patrick Nshimiyimana', email: 'patrick.nshimi@onlineshop.rw', createdDaysAgo: 40 },
        slug: 'acacia-living',
        status: 'APPROVED',
        registeredName: 'Acacia Living Ltd',
        displayName: 'Acacia Living',
        description: 'Clay vases and handwoven runners for dining tables.',
        aboutUs: 'Acacia sources clay from Rulindo and weaves runners on two looms behind the shop.',
        contactAddress: 'Remera, Kigali',
        industryCode: 'HOME_LIVING',
        categoryCode: 'HOME_DECOR',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Kigali',
            district: 'Gasabo',
            sector: 'Remera',
            physicalAddress: 'KG 17 Ave',
            googleMapsUrl: 'https://maps.google.com/?q=Remera+Kigali',
        },
        ratingAvg: 4.5,
        ratingCount: 5,
        approvedDaysAgo: 36,
        createdDaysAgo: 39,
        brandColors: { primary: '#78716c', secondary: '#1c1917', template: 'ISHUSHO_CRAFTS' },
    },
    {
        owner: { phoneNumber: '+233200000031', fullName: 'Lydia Wambui', email: 'lydia.wambui@onlineshop.rw', createdDaysAgo: 37 },
        slug: 'nile-sports',
        status: 'APPROVED',
        registeredName: 'Nile Sports Ltd',
        displayName: 'Nile Sports',
        description: 'Jump ropes, blocks, and compact gym tools for home workouts.',
        aboutUs: 'Nile started in a shared studio and still trains with everything it sells.',
        contactAddress: 'Jinja Road, Kampala',
        industryCode: 'SPORTS_FITNESS',
        categoryCode: 'GYM',
        country: 'UG',
        ownerNationality: 'Ugandan',
        address: {
            province: 'Central',
            district: 'Kampala',
            sector: 'Nakawa',
            physicalAddress: '12 Jinja Road',
            googleMapsUrl: 'https://maps.google.com/?q=Nakawa+Kampala',
        },
        ratingAvg: 4.0,
        ratingCount: 2,
        approvedDaysAgo: 33,
        createdDaysAgo: 36,
        brandColors: { primary: '#16a34a', secondary: '#052e16', template: 'DEFAULT' },
    },
]

const PIPELINE_OWNERS: CatalogPerson[] = [
    { phoneNumber: '+233200000040', fullName: 'Helena Dlamini', email: 'helena.dlamini@onlineshop.rw', createdDaysAgo: 14 },
    { phoneNumber: '+233200000041', fullName: 'Boubacar Sy', email: 'boubacar.sy@onlineshop.rw', createdDaysAgo: 13 },
    { phoneNumber: '+233200000042', fullName: 'Irene Nyirahabimana', email: 'irene.nyira@onlineshop.rw', createdDaysAgo: 12 },
    { phoneNumber: '+233200000043', fullName: 'Michael Owusu', email: 'michael.owusu@onlineshop.rw', createdDaysAgo: 11 },
    { phoneNumber: '+233200000044', fullName: 'Salma Hassan', email: 'salma.hassan@onlineshop.rw', createdDaysAgo: 10 },
    { phoneNumber: '+233200000045', fullName: 'Peter Mwangi', email: 'peter.mwangi@onlineshop.rw', createdDaysAgo: 10 },
    { phoneNumber: '+233200000046', fullName: 'Adwoa Frimpong', email: 'adwoa.frimpong@onlineshop.rw', createdDaysAgo: 9 },
    { phoneNumber: '+233200000047', fullName: 'Yvette Uwimana', email: 'yvette.uwimana@onlineshop.rw', createdDaysAgo: 8 },
    { phoneNumber: '+233200000048', fullName: 'Collins Adebola', email: 'collins.adebola@onlineshop.rw', createdDaysAgo: 22 },
    { phoneNumber: '+233200000049', fullName: 'Hawa Camara', email: 'hawa.camara@onlineshop.rw', createdDaysAgo: 21 },
    { phoneNumber: '+233200000050', fullName: 'Eric Nkurunziza', email: 'eric.nkurunziza@onlineshop.rw', createdDaysAgo: 19 },
    { phoneNumber: '+233200000051', fullName: 'Blessing Okoro', email: 'blessing.okoro@onlineshop.rw', createdDaysAgo: 17 },
    { phoneNumber: '+233200000052', fullName: 'Aminata Ba', email: 'aminata.ba@onlineshop.rw', status: 'SUSPENDED', createdDaysAgo: 34 },
    { phoneNumber: '+233200000053', fullName: 'George Otieno', email: 'george.otieno@onlineshop.rw', status: 'SUSPENDED', createdDaysAgo: 32 },
    { phoneNumber: '+233200000054', fullName: 'Cynthia Mensah', email: 'cynthia.mensah@onlineshop.rw', status: 'SUSPENDED', createdDaysAgo: 30 },
    { phoneNumber: '+233200000055', fullName: 'Alain Bizimana', email: 'alain.bizimana@onlineshop.rw', status: 'SUSPENDED', createdDaysAgo: 28 },
]

export const EXTRA_PIPELINE_STORES: CatalogStore[] = [
    {
        owner: PIPELINE_OWNERS[0],
        slug: 'coastal-staples',
        status: 'SUBMITTED',
        registeredName: 'Coastal Staples Ltd',
        displayName: 'Coastal Staples',
        description: 'Dry goods shop waiting on document review.',
        aboutUs: 'A family pantry shop applying to sell rice, oil, and spices.',
        contactAddress: 'Takoradi Market Circle',
        industryCode: 'RETAIL',
        categoryCode: 'MINI_MARKET',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Western',
            district: 'Sekondi-Takoradi',
            sector: 'Market Circle',
            physicalAddress: '3 Market Circle',
            googleMapsUrl: 'https://maps.google.com/?q=Takoradi+Market+Circle',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 14,
        brandColors: { primary: '#1daf61', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[1],
        slug: 'sahel-threads',
        status: 'SUBMITTED',
        registeredName: 'Sahel Threads Ltd',
        displayName: 'Sahel Threads',
        description: 'New clothing stall still collecting KYC files.',
        aboutUs: 'Ready-to-wear shirts and trousers for the dry season.',
        contactAddress: 'Medina, Dakar',
        industryCode: 'FASHION_APPAREL',
        categoryCode: 'CLOTHING_STORE',
        country: 'SN',
        ownerNationality: 'Senegalese',
        address: {
            province: 'Dakar',
            district: 'Dakar',
            sector: 'Medina',
            physicalAddress: '17 Avenue Blaise Diagne',
            googleMapsUrl: 'https://maps.google.com/?q=Medina+Dakar',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 13,
        brandColors: { primary: '#db2777', secondary: '#171717', template: 'ISHUSHO_CRAFTS' },
    },
    {
        owner: PIPELINE_OWNERS[2],
        slug: 'inkuru-books',
        status: 'SUBMITTED',
        registeredName: 'Inkuru Books Ltd',
        displayName: 'Inkuru Books',
        description: 'Bookstore application submitted this week.',
        aboutUs: 'School readers and local novels packed from a Kigali spare room.',
        contactAddress: 'Nyamirambo, Kigali',
        industryCode: 'EDUCATION_TRAINING',
        categoryCode: 'BOOKSTORE',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Kigali',
            district: 'Nyarugenge',
            sector: 'Nyamirambo',
            physicalAddress: 'KN 20 St',
            googleMapsUrl: 'https://maps.google.com/?q=Nyamirambo+Kigali',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 12,
        brandColors: { primary: '#2563eb', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[3],
        slug: 'harbor-spares',
        status: 'SUBMITTED',
        registeredName: 'Harbor Spares Ltd',
        displayName: 'Harbor Spares',
        description: 'Auto parts counter waiting for approval.',
        aboutUs: 'Filters and bulbs for common city cars.',
        contactAddress: 'Tema Community 4',
        industryCode: 'AUTOMOTIVE',
        categoryCode: 'AUTO_PARTS',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Greater Accra',
            district: 'Tema',
            sector: 'Community 4',
            physicalAddress: 'Harbour Industrial Area',
            googleMapsUrl: 'https://maps.google.com/?q=Tema+Community+4',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 11,
        brandColors: { primary: '#334155', secondary: '#0f172a', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[4],
        slug: 'oasis-spa-shop',
        status: 'UNDER_REVIEW',
        registeredName: 'Oasis Spa Shop Ltd',
        displayName: 'Oasis Spa Shop',
        description: 'Documents are with the review desk.',
        aboutUs: 'Oils and towels for small salon counters.',
        contactAddress: 'Mombasa Road, Nairobi',
        industryCode: 'BEAUTY_PERSONAL_CARE',
        categoryCode: 'SPA',
        country: 'KE',
        ownerNationality: 'Kenyan',
        address: {
            province: 'Nairobi',
            district: 'Embakasi',
            sector: 'Industrial Area',
            physicalAddress: 'Mombasa Road warehouse 2',
            googleMapsUrl: 'https://maps.google.com/?q=Mombasa+Road+Nairobi',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 10,
        brandColors: { primary: '#db2777', secondary: '#171717', template: 'VIBRANT_MARKET' },
    },
    {
        owner: PIPELINE_OWNERS[5],
        slug: 'ridge-hardware',
        status: 'UNDER_REVIEW',
        registeredName: 'Ridge Hardware Ltd',
        displayName: 'Ridge Hardware',
        description: 'Platform team is checking supplier invoices.',
        aboutUs: 'Fasteners and hand tools for estate repairs.',
        contactAddress: 'Industrial Area, Nairobi',
        industryCode: 'CONSTRUCTION',
        categoryCode: 'BUILDING_MATERIALS',
        country: 'KE',
        ownerNationality: 'Kenyan',
        address: {
            province: 'Nairobi',
            district: 'Starehe',
            sector: 'Industrial Area',
            physicalAddress: 'Enterprise Road',
            googleMapsUrl: 'https://maps.google.com/?q=Enterprise+Road+Nairobi',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 10,
        brandColors: { primary: '#78716c', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[6],
        slug: 'gold-coast-audio',
        status: 'UNDER_REVIEW',
        registeredName: 'Gold Coast Audio Ltd',
        displayName: 'Gold Coast Audio',
        description: 'Reviewing warranty paperwork.',
        aboutUs: 'Used and refurbished speakers with a 30-day bench test.',
        contactAddress: 'Osu, Accra',
        industryCode: 'ELECTRONICS_TECH',
        categoryCode: 'ACCESSORY_SHOP',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Greater Accra',
            district: 'Accra Metro',
            sector: 'Osu',
            physicalAddress: 'Oxford Street annex',
            googleMapsUrl: 'https://maps.google.com/?q=Osu+Oxford+Street',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 9,
        brandColors: { primary: '#2563eb', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[7],
        slug: 'intore-fitness',
        status: 'UNDER_REVIEW',
        registeredName: 'Intore Fitness Ltd',
        displayName: 'Intore Fitness',
        description: 'Coach certificates are being verified.',
        aboutUs: 'Home gym kits assembled in Kicukiro.',
        contactAddress: 'Kicukiro, Kigali',
        industryCode: 'SPORTS_FITNESS',
        categoryCode: 'FITNESS_COACH',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Kigali',
            district: 'Kicukiro',
            sector: 'Gatenga',
            physicalAddress: 'KK 15 Ave',
            googleMapsUrl: 'https://maps.google.com/?q=Gatenga+Kigali',
        },
        ratingAvg: 0,
        ratingCount: 0,
        createdDaysAgo: 8,
        brandColors: { primary: '#16a34a', secondary: '#171717', template: 'VIBRANT_MARKET' },
    },
    {
        owner: PIPELINE_OWNERS[8],
        slug: 'red-earth-goods',
        status: 'REJECTED',
        registeredName: 'Red Earth Goods Ltd',
        displayName: 'Red Earth Goods',
        description: 'Application did not pass document checks.',
        aboutUs: 'Attempted grocery stall with incomplete tax files.',
        contactAddress: 'Ibadan New Gbagi',
        industryCode: 'RETAIL',
        categoryCode: 'GENERAL_STORE',
        country: 'NG',
        ownerNationality: 'Nigerian',
        address: {
            province: 'Oyo',
            district: 'Ibadan',
            sector: 'Gbagi',
            physicalAddress: 'New Gbagi Market lockup 12',
            googleMapsUrl: 'https://maps.google.com/?q=Gbagi+Ibadan',
        },
        ratingAvg: 0,
        ratingCount: 0,
        rejectionReason: 'Business registration number could not be verified.',
        createdDaysAgo: 22,
        brandColors: { primary: '#1daf61', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[9],
        slug: 'faded-linen',
        status: 'REJECTED',
        registeredName: 'Faded Linen Ltd',
        displayName: 'Faded Linen',
        description: 'Rejected after incomplete owner identification.',
        aboutUs: 'A linen shop that never finished KYC.',
        contactAddress: 'Bamako centre',
        industryCode: 'FASHION_APPAREL',
        categoryCode: 'TAILORING',
        country: 'ML',
        ownerNationality: 'Malian',
        address: {
            province: 'Bamako',
            district: 'Commune III',
            sector: 'Centre',
            physicalAddress: 'Rue 312',
            googleMapsUrl: 'https://maps.google.com/?q=Bamako+Commune+III',
        },
        ratingAvg: 0,
        ratingCount: 0,
        rejectionReason: 'Owner identification photos were unreadable.',
        createdDaysAgo: 21,
        brandColors: { primary: '#db2777', secondary: '#171717', template: 'ISHUSHO_CRAFTS' },
    },
    {
        owner: PIPELINE_OWNERS[10],
        slug: 'broken-circuit',
        status: 'REJECTED',
        registeredName: 'Broken Circuit Ltd',
        displayName: 'Broken Circuit',
        description: 'Rejected for selling unsupported refurbished phones.',
        aboutUs: 'Phone stall that listed devices without serial records.',
        contactAddress: 'Nyabugogo, Kigali',
        industryCode: 'ELECTRONICS_TECH',
        categoryCode: 'PHONE_SHOP',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Kigali',
            district: 'Nyarugenge',
            sector: 'Nyabugogo',
            physicalAddress: 'Nyabugogo taxi park stall 9',
            googleMapsUrl: 'https://maps.google.com/?q=Nyabugogo+Kigali',
        },
        ratingAvg: 0,
        ratingCount: 0,
        rejectionReason: 'Refurbished devices lacked serial and warranty records.',
        createdDaysAgo: 19,
        brandColors: { primary: '#2563eb', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[11],
        slug: 'dry-season-mart',
        status: 'REJECTED',
        registeredName: 'Dry Season Mart Ltd',
        displayName: 'Dry Season Mart',
        description: 'Rejected after a mismatched bank account name.',
        aboutUs: 'A bulk rice trader whose payout account did not match KYC.',
        contactAddress: 'Tamale Central',
        industryCode: 'WHOLESALE',
        categoryCode: 'BULK_DISTRIBUTOR',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Northern',
            district: 'Tamale',
            sector: 'Central',
            physicalAddress: 'Aboabo market row 4',
            googleMapsUrl: 'https://maps.google.com/?q=Tamale+Aboabo+Market',
        },
        ratingAvg: 0,
        ratingCount: 0,
        rejectionReason: 'Payout account name did not match the registered business.',
        createdDaysAgo: 17,
        brandColors: { primary: '#1daf61', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[12],
        slug: 'quiet-aisle',
        status: 'SUSPENDED',
        registeredName: 'Quiet Aisle Ltd',
        displayName: 'Quiet Aisle',
        description: 'Temporarily paused after repeated late fulfillments.',
        aboutUs: 'A grocery shop paused while delivery SLAs are reviewed.',
        contactAddress: 'Cape Coast',
        industryCode: 'RETAIL',
        categoryCode: 'SUPERMARKET',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Central',
            district: 'Cape Coast',
            sector: 'Kotokuraba',
            physicalAddress: 'Kotokuraba Market',
            googleMapsUrl: 'https://maps.google.com/?q=Cape+Coast+Kotokuraba',
        },
        ratingAvg: 3.1,
        ratingCount: 6,
        approvedDaysAgo: 30,
        createdDaysAgo: 34,
        brandColors: { primary: '#1daf61', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[13],
        slug: 'paused-pixels',
        status: 'SUSPENDED',
        registeredName: 'Paused Pixels Ltd',
        displayName: 'Paused Pixels',
        description: 'Suspended pending a customer complaint review.',
        aboutUs: 'An accessories stall paused after two chargeback cases.',
        contactAddress: 'Kisumu CBD',
        industryCode: 'ELECTRONICS_TECH',
        categoryCode: 'ACCESSORY_SHOP',
        country: 'KE',
        ownerNationality: 'Kenyan',
        address: {
            province: 'Kisumu',
            district: 'Kisumu Central',
            sector: 'CBD',
            physicalAddress: 'Oginga Odinga Street',
            googleMapsUrl: 'https://maps.google.com/?q=Oginga+Odinga+Street+Kisumu',
        },
        ratingAvg: 2.8,
        ratingCount: 5,
        approvedDaysAgo: 28,
        createdDaysAgo: 32,
        brandColors: { primary: '#2563eb', secondary: '#171717', template: 'DEFAULT' },
    },
    {
        owner: PIPELINE_OWNERS[14],
        slug: 'held-hanger',
        status: 'SUSPENDED',
        registeredName: 'Held Hanger Ltd',
        displayName: 'Held Hanger',
        description: 'Suspended for listing counterfeit-branded tees.',
        aboutUs: 'Fashion stall paused while listings are cleaned up.',
        contactAddress: 'Kumasi Kejetia',
        industryCode: 'FASHION_APPAREL',
        categoryCode: 'CLOTHING_STORE',
        country: 'GH',
        ownerNationality: 'Ghanaian',
        address: {
            province: 'Ashanti',
            district: 'Kumasi',
            sector: 'Kejetia',
            physicalAddress: 'Kejetia Market line 8',
            googleMapsUrl: 'https://maps.google.com/?q=Kejetia+Market+Kumasi',
        },
        ratingAvg: 3.4,
        ratingCount: 8,
        approvedDaysAgo: 26,
        createdDaysAgo: 30,
        brandColors: { primary: '#db2777', secondary: '#171717', template: 'VIBRANT_MARKET' },
    },
    {
        owner: PIPELINE_OWNERS[15],
        slug: 'frozen-aisle',
        status: 'SUSPENDED',
        registeredName: 'Frozen Aisle Ltd',
        displayName: 'Frozen Aisle',
        description: 'Suspended after cold-chain delivery failures.',
        aboutUs: 'A pantry shop paused until insulated packaging is confirmed.',
        contactAddress: 'Gisozi, Kigali',
        industryCode: 'FOOD_BEVERAGE',
        categoryCode: 'FOOD_PROCESSING',
        country: 'RW',
        ownerNationality: 'Rwandan',
        address: {
            province: 'Kigali',
            district: 'Gasabo',
            sector: 'Gisozi',
            physicalAddress: 'KG 8 Ave',
            googleMapsUrl: 'https://maps.google.com/?q=Gisozi+Kigali',
        },
        ratingAvg: 3.0,
        ratingCount: 4,
        approvedDaysAgo: 24,
        createdDaysAgo: 28,
        brandColors: { primary: '#b91c1c', secondary: '#171717', template: 'DEFAULT' },
    },
]

export const EXTRA_PRODUCTS: CatalogProduct[] = [
    {
        storeSlug: 'harvest-market',
        name: 'Highland Honey',
        description: 'Raw highland honey strained once and packed in glass.',
        vendor: 'Harvest Market',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'ACTIVE',
        tags: ['honey', 'pantry', 'raw'],
        attributes: { organic: true, origin: 'Western Highlands' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 48,
        variants: [
            { sku: 'HV-HONEY-250', title: '250g', size: '250g', model: 'Glass jar', price: 9000, cost: 4200, stock: 64, attributes: { weight: '250g' } },
            { sku: 'HV-HONEY-500', title: '500g', size: '500g', model: 'Glass jar', price: 16500, cost: 7800, stock: 27, attributes: { weight: '500g' } },
        ],
    },
    {
        storeSlug: 'harvest-market',
        name: 'Red Palm Oil',
        description: 'Unrefined red palm oil pressed for everyday stews.',
        vendor: 'Harvest Market',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'ACTIVE',
        tags: ['oil', 'cooking', 'staple'],
        attributes: { organic: false, origin: 'Volta' },
        deliveryPrice: 2000,
        deliveryLocation: 'Outer districts',
        createdDaysAgo: 42,
        variants: [
            { sku: 'HV-PALM-500', title: '500ml', size: '500ml', model: 'Bottle', price: 7000, cost: 3200, stock: 51, attributes: { weight: '500ml' } },
            { sku: 'HV-PALM-1L', title: '1L', size: '1L', model: 'Bottle', price: 12500, cost: 5800, stock: 19, attributes: { weight: '1L' } },
        ],
    },
    {
        storeSlug: 'harvest-market',
        name: 'Plantain Chips',
        description: 'Lightly salted plantain chips fried the morning they ship.',
        vendor: 'Harvest Market',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'ACTIVE',
        tags: ['snacks', 'plantain'],
        attributes: { organic: false },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 28,
        variants: [
            { sku: 'HV-CHIP-150', title: '150g', size: '150g', model: 'Share bag', price: 3500, cost: 1400, stock: 90, attributes: { weight: '150g' } },
            { sku: 'HV-CHIP-300', title: '300g', size: '300g', model: 'Family bag', price: 6000, cost: 2500, stock: 7, reserved: 1, attributes: { weight: '300g' } },
        ],
    },
    {
        storeSlug: 'harvest-market',
        name: 'Dried Hibiscus',
        description: 'Sun-dried hibiscus petals for cold tea.',
        vendor: 'Harvest Market',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'ACTIVE',
        tags: ['tea', 'hibiscus'],
        attributes: { organic: true },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 21,
        variants: [{ sku: 'HV-HIB-100', title: '100g', size: '100g', model: 'Pouch', price: 4500, cost: 1800, stock: 38, attributes: { weight: '100g' } }],
    },
    {
        storeSlug: 'northline-electronics',
        name: 'Harbor Bluetooth Speaker',
        description: 'Compact speaker with a 12-hour battery and local warranty.',
        vendor: 'Northline',
        category: 'Electronics',
        categorySlug: 'electronics',
        status: 'ACTIVE',
        tags: ['audio', 'speaker', 'bluetooth'],
        attributes: { brand: 'Harbor', warranty_months: 12 },
        deliveryPrice: 2500,
        deliveryLocation: 'City center',
        createdDaysAgo: 33,
        variants: [
            { sku: 'NL-SPK-BLK', title: 'Black', colorName: 'Black', colorHex: '#111111', model: 'Mini', price: 38000, cost: 21000, stock: 16, attributes: { storage_gb: 0 } },
            { sku: 'NL-SPK-BLU', title: 'Ocean', colorName: 'Ocean', colorHex: '#1d4ed8', model: 'Mini', price: 38000, cost: 21000, stock: 9, attributes: { storage_gb: 0 } },
        ],
    },
    {
        storeSlug: 'northline-electronics',
        name: 'Power Bank 20000mAh',
        description: 'Two-port power bank for phones and small tablets.',
        vendor: 'Northline',
        category: 'Electronics',
        categorySlug: 'electronics',
        status: 'ACTIVE',
        tags: ['power', 'travel'],
        attributes: { brand: 'Northline', warranty_months: 6 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 24,
        variants: [{ sku: 'NL-PB-20K', title: '20000mAh', model: '20K', price: 22000, cost: 12000, stock: 41, attributes: { storage_gb: 0 } }],
    },
    {
        storeSlug: 'northline-electronics',
        name: 'Quiet Wireless Mouse',
        description: 'Low-click mouse for shared desks.',
        vendor: 'Northline',
        category: 'Electronics',
        categorySlug: 'electronics',
        status: 'ACTIVE',
        tags: ['mouse', 'desk'],
        attributes: { brand: 'Northline', warranty_months: 12 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 18,
        variants: [
            { sku: 'NL-MOU-BLK', title: 'Black', colorName: 'Black', colorHex: '#171717', model: 'Quiet', price: 14000, cost: 6500, stock: 33 },
            { sku: 'NL-MOU-GRY', title: 'Grey', colorName: 'Grey', colorHex: '#6b7280', model: 'Quiet', price: 14000, cost: 6500, stock: 5, reserved: 1 },
        ],
    },
    {
        storeSlug: 'northline-electronics',
        name: 'Glass Screen Protector Pack',
        description: 'Retired two-pack kept for older order history.',
        vendor: 'Northline',
        category: 'Electronics',
        categorySlug: 'electronics',
        status: 'ARCHIVED',
        tags: ['screen', 'spare'],
        attributes: { brand: 'Northline', warranty_months: 1 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 44,
        variants: [{ sku: 'NL-GLASS-OLD', title: 'Universal', model: 'Legacy', price: 6000, cost: 2000, stock: 0 }],
    },
    {
        storeSlug: 'atelier-threads',
        name: 'Linen Shirt Dress',
        description: 'Breathable linen dress with side pockets.',
        vendor: 'Atelier Threads',
        category: 'Fashion',
        categorySlug: 'fashion',
        status: 'ACTIVE',
        tags: ['linen', 'dress'],
        attributes: { material: 'Linen' },
        deliveryPrice: 2000,
        deliveryLocation: 'City center',
        createdDaysAgo: 29,
        variants: [
            { sku: 'AT-DRS-SND-S', title: 'Sand / S', colorName: 'Sand', colorHex: '#e7d3b0', size: 'S', model: 'Shirt dress', price: 32000, cost: 15000, stock: 12, attributes: { size: 'S', color: 'Sand' } },
            { sku: 'AT-DRS-SND-M', title: 'Sand / M', colorName: 'Sand', colorHex: '#e7d3b0', size: 'M', model: 'Shirt dress', price: 32000, cost: 15000, stock: 18, attributes: { size: 'M', color: 'Sand' } },
            { sku: 'AT-DRS-INK-M', title: 'Ink / M', colorName: 'Ink', colorHex: '#1e293b', size: 'M', model: 'Shirt dress', price: 32000, cost: 15000, stock: 6, attributes: { size: 'M', color: 'Ink' } },
        ],
    },
    {
        storeSlug: 'atelier-threads',
        name: 'Canvas Slip-Ons',
        description: 'Everyday canvas shoes with a rubber sole.',
        vendor: 'Atelier Threads',
        category: 'Fashion',
        categorySlug: 'fashion',
        status: 'ACTIVE',
        tags: ['shoes', 'canvas'],
        attributes: { material: 'Canvas' },
        deliveryPrice: 2000,
        deliveryLocation: 'City center',
        createdDaysAgo: 22,
        variants: [
            { sku: 'AT-SLIP-WHT-40', title: 'White / 40', colorName: 'White', colorHex: '#f8f8f8', size: '40', model: 'Slip-on', price: 28000, cost: 13000, stock: 14, attributes: { size: '40', color: 'White' } },
            { sku: 'AT-SLIP-WHT-42', title: 'White / 42', colorName: 'White', colorHex: '#f8f8f8', size: '42', model: 'Slip-on', price: 28000, cost: 13000, stock: 8, attributes: { size: '42', color: 'White' } },
            { sku: 'AT-SLIP-NVY-42', title: 'Navy / 42', colorName: 'Navy', colorHex: '#1e3a5f', size: '42', model: 'Slip-on', price: 28000, cost: 13000, stock: 3, attributes: { size: '42', color: 'Navy' } },
        ],
    },
    {
        storeSlug: 'atelier-threads',
        name: 'Wax Print Scarf',
        description: 'Lightweight wax-print scarf for sun and dust.',
        vendor: 'Atelier Threads',
        category: 'Fashion',
        categorySlug: 'fashion',
        status: 'ACTIVE',
        tags: ['scarf', 'wax-print'],
        attributes: { material: 'Cotton wax print' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 16,
        variants: [
            { sku: 'AT-SCF-RED', title: 'Market red', colorName: 'Market red', colorHex: '#b91c1c', model: 'Square', price: 12000, cost: 4500, stock: 22, attributes: { color: 'Market red' } },
            { sku: 'AT-SCF-GLD', title: 'Gold dust', colorName: 'Gold dust', colorHex: '#ca8a04', model: 'Square', price: 12000, cost: 4500, stock: 17, attributes: { color: 'Gold dust' } },
        ],
    },
    {
        storeSlug: 'lakeview-pharmacy',
        name: 'Immune Vitamin C Tablets',
        description: 'Chewable vitamin C bottled in 30 and 60 counts.',
        vendor: 'Lakeview Pharmacy',
        category: 'Health',
        categorySlug: 'health',
        status: 'ACTIVE',
        tags: ['vitamins', 'immunity'],
        attributes: { form: 'Tablet', count: 30 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 40,
        variants: [
            { sku: 'LV-VITC-30', title: '30 tablets', size: '30', model: 'Bottle', price: 6500, cost: 2800, stock: 70, attributes: { count: 30 } },
            { sku: 'LV-VITC-60', title: '60 tablets', size: '60', model: 'Bottle', price: 11000, cost: 4900, stock: 24, attributes: { count: 60 } },
        ],
    },
    {
        storeSlug: 'lakeview-pharmacy',
        name: 'Herbal Cough Syrup',
        description: 'Honey-and-ginger syrup for dry evening coughs.',
        vendor: 'Lakeview Pharmacy',
        category: 'Health',
        categorySlug: 'health',
        status: 'ACTIVE',
        tags: ['syrup', 'cold'],
        attributes: { form: 'Syrup', count: 1 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 27,
        variants: [{ sku: 'LV-SYR-100', title: '100ml', size: '100ml', model: 'Bottle', price: 8000, cost: 3100, stock: 36, attributes: { count: 1 } }],
    },
    {
        storeSlug: 'savanna-home',
        name: 'Acacia Side Table',
        description: 'Low acacia table sized for a sofa arm.',
        vendor: 'Savanna Home',
        category: 'Home',
        categorySlug: 'home',
        status: 'ACTIVE',
        tags: ['furniture', 'wood'],
        attributes: { material: 'Acacia', room: 'Living room' },
        deliveryPrice: 5000,
        deliveryLocation: 'Outer districts',
        createdDaysAgo: 35,
        variants: [
            { sku: 'SH-TAB-NAT', title: 'Natural', colorName: 'Natural', colorHex: '#c4a574', model: 'Side table', price: 85000, cost: 42000, stock: 8, attributes: { material: 'Acacia' } },
            { sku: 'SH-TAB-EBONY', title: 'Ebony stain', colorName: 'Ebony', colorHex: '#1c1917', model: 'Side table', price: 89000, cost: 45000, stock: 4, attributes: { material: 'Acacia' } },
        ],
    },
    {
        storeSlug: 'savanna-home',
        name: 'Woven Floor Cushion',
        description: 'Thick floor cushion with a removable cover.',
        vendor: 'Savanna Home',
        category: 'Home',
        categorySlug: 'home',
        status: 'ACTIVE',
        tags: ['textile', 'cushion'],
        attributes: { material: 'Cotton weave', room: 'Living room' },
        deliveryPrice: 2500,
        deliveryLocation: 'City center',
        createdDaysAgo: 19,
        variants: [
            { sku: 'SH-CSH-CLAY', title: 'Clay', colorName: 'Clay', colorHex: '#b45309', model: 'Floor', price: 18000, cost: 8000, stock: 15 },
            { sku: 'SH-CSH-SAGE', title: 'Sage', colorName: 'Sage', colorHex: '#4d7c0f', model: 'Floor', price: 18000, cost: 8000, stock: 11 },
        ],
    },
    {
        storeSlug: 'bloom-beauty',
        name: 'Shea Body Butter',
        description: 'Whipped shea butter with a light citrus scent.',
        vendor: 'Bloom Beauty',
        category: 'Beauty',
        categorySlug: 'beauty',
        status: 'ACTIVE',
        tags: ['shea', 'body'],
        attributes: { skin_type: 'Dry', volume: '200ml' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 31,
        variants: [
            { sku: 'BB-SHEA-200', title: '200ml', size: '200ml', model: 'Jar', price: 9500, cost: 3800, stock: 48, attributes: { volume: '200ml' } },
            { sku: 'BB-SHEA-400', title: '400ml', size: '400ml', model: 'Jar', price: 16000, cost: 6400, stock: 13, attributes: { volume: '400ml' } },
        ],
    },
    {
        storeSlug: 'bloom-beauty',
        name: 'Hibiscus Hair Oil',
        description: 'Light hibiscus oil for braids and wash day.',
        vendor: 'Bloom Beauty',
        category: 'Beauty',
        categorySlug: 'beauty',
        status: 'ACTIVE',
        tags: ['hair', 'oil'],
        attributes: { skin_type: 'All', volume: '100ml' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 17,
        variants: [{ sku: 'BB-HAIR-100', title: '100ml', size: '100ml', model: 'Dropper', price: 7500, cost: 2900, stock: 29, attributes: { volume: '100ml' } }],
    },
    {
        storeSlug: 'peak-athletics',
        name: 'Trail Running Shoes',
        description: 'Mesh trail shoes with a grippy rubber outsole.',
        vendor: 'Peak Athletics',
        category: 'Sports',
        categorySlug: 'sports',
        status: 'ACTIVE',
        tags: ['running', 'shoes'],
        attributes: { sport: 'Running', size: '42' },
        deliveryPrice: 2500,
        deliveryLocation: 'City center',
        createdDaysAgo: 26,
        variants: [
            { sku: 'PA-SHOE-41', title: 'Slate / 41', colorName: 'Slate', colorHex: '#334155', size: '41', model: 'Trail', price: 54000, cost: 28000, stock: 10, attributes: { size: '41' } },
            { sku: 'PA-SHOE-43', title: 'Slate / 43', colorName: 'Slate', colorHex: '#334155', size: '43', model: 'Trail', price: 54000, cost: 28000, stock: 7, attributes: { size: '43' } },
            { sku: 'PA-SHOE-43-ORG', title: 'Blaze / 43', colorName: 'Blaze', colorHex: '#ea580c', size: '43', model: 'Trail', price: 56000, cost: 29000, stock: 4, attributes: { size: '43' } },
        ],
    },
    {
        storeSlug: 'peak-athletics',
        name: 'Resistance Band Set',
        description: 'Three-band set with a carry pouch.',
        vendor: 'Peak Athletics',
        category: 'Sports',
        categorySlug: 'sports',
        status: 'ACTIVE',
        tags: ['training', 'bands'],
        attributes: { sport: 'Strength', size: 'Set' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 14,
        variants: [{ sku: 'PA-BAND-3', title: '3-pack', model: 'Studio', price: 16000, cost: 7000, stock: 26 }],
    },
    {
        storeSlug: 'little-baobab',
        name: 'Wooden Puzzle Set',
        description: 'Four animal puzzles cut from leftover workshop wood.',
        vendor: 'Little Baobab',
        category: 'General',
        categorySlug: 'general',
        status: 'ACTIVE',
        tags: ['toys', 'wood'],
        attributes: { condition: 'New' },
        deliveryPrice: 2000,
        deliveryLocation: 'City center',
        createdDaysAgo: 25,
        variants: [{ sku: 'LB-PUZ-4', title: '4 puzzles', model: 'Starter', price: 14000, cost: 6000, stock: 20 }],
    },
    {
        storeSlug: 'little-baobab',
        name: 'Soft Cotton Onesie',
        description: 'Pre-washed cotton onesie with envelope shoulders.',
        vendor: 'Little Baobab',
        category: 'Fashion',
        categorySlug: 'fashion',
        status: 'ACTIVE',
        tags: ['baby', 'cotton'],
        attributes: { material: 'Cotton' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 13,
        variants: [
            { sku: 'LB-ONE-CRM-70', title: 'Cream / 70', colorName: 'Cream', colorHex: '#f5f0e6', size: '70', model: 'Onesie', price: 9000, cost: 3500, stock: 18, attributes: { size: '70', color: 'Cream' } },
            { sku: 'LB-ONE-SKY-80', title: 'Sky / 80', colorName: 'Sky', colorHex: '#7dd3fc', size: '80', model: 'Onesie', price: 9000, cost: 3500, stock: 12, attributes: { size: '80', color: 'Sky' } },
        ],
    },
    {
        storeSlug: 'kigali-pantry',
        name: 'Akabanga Chili Oil',
        description: 'Rwandan chili oil in the familiar dropper bottle.',
        vendor: 'Kigali Pantry',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'ACTIVE',
        tags: ['chili', 'condiment'],
        attributes: { organic: false },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 20,
        variants: [
            { sku: 'KP-AKA-50', title: '50ml', size: '50ml', model: 'Dropper', price: 4000, cost: 1500, stock: 80, attributes: { weight: '50ml' } },
            { sku: 'KP-AKA-125', title: '125ml', size: '125ml', model: 'Dropper', price: 7500, cost: 2800, stock: 22, attributes: { weight: '125ml' } },
        ],
    },
    {
        storeSlug: 'kigali-pantry',
        name: 'Banana Wine',
        description: 'Draft listing for the next tasting batch.',
        vendor: 'Kigali Pantry',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'DRAFT',
        tags: ['wine', 'banana'],
        attributes: { organic: false },
        deliveryPrice: 2500,
        deliveryLocation: 'City center',
        createdDaysAgo: 5,
        variants: [{ sku: 'KP-WINE-750', title: '750ml', size: '750ml', model: 'Bottle', price: 12000, cost: 5000, stock: 16, attributes: { weight: '750ml' } }],
    },
    {
        storeSlug: 'volta-gadgets',
        name: 'Compact Laptop Stand',
        description: 'Folding aluminum stand for 13–16 inch laptops.',
        vendor: 'Volta Gadgets',
        category: 'Electronics',
        categorySlug: 'electronics',
        status: 'ACTIVE',
        tags: ['desk', 'laptop'],
        attributes: { brand: 'Volta', warranty_months: 12 },
        deliveryPrice: 2000,
        deliveryLocation: 'City center',
        createdDaysAgo: 23,
        variants: [
            { sku: 'VG-STAND-SLV', title: 'Silver', colorName: 'Silver', colorHex: '#c0c0c0', model: 'Fold', price: 24000, cost: 11000, stock: 19 },
            { sku: 'VG-STAND-BLK', title: 'Black', colorName: 'Black', colorHex: '#111111', model: 'Fold', price: 24000, cost: 11000, stock: 8 },
        ],
    },
    {
        storeSlug: 'volta-gadgets',
        name: 'USB-C Hub 7-in-1',
        description: 'HDMI, USB-A, SD, and charging passthrough.',
        vendor: 'Volta Gadgets',
        category: 'Electronics',
        categorySlug: 'electronics',
        status: 'ACTIVE',
        tags: ['hub', 'usb-c'],
        attributes: { brand: 'Volta', warranty_months: 12 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 11,
        variants: [{ sku: 'VG-HUB-7', title: '7-in-1', model: 'Travel', price: 19000, cost: 9000, stock: 27 }],
    },
    {
        storeSlug: 'umuco-atelier',
        name: 'Kitenge Tote Bag',
        description: 'Market tote cut from leftover kitenge bolts.',
        vendor: 'Umuco Atelier',
        category: 'Fashion',
        categorySlug: 'fashion',
        status: 'ACTIVE',
        tags: ['bag', 'kitenge'],
        attributes: { material: 'Kitenge cotton' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 18,
        variants: [
            { sku: 'UA-TOTE-IND', title: 'Indigo market', colorName: 'Indigo', colorHex: '#312e81', model: 'Tote', price: 16000, cost: 6000, stock: 21, attributes: { color: 'Indigo' } },
            { sku: 'UA-TOTE-SUN', title: 'Sunburst', colorName: 'Sunburst', colorHex: '#f59e0b', model: 'Tote', price: 16000, cost: 6000, stock: 14, attributes: { color: 'Sunburst' } },
        ],
    },
    {
        storeSlug: 'umuco-atelier',
        name: 'Beaded Bracelet Set',
        description: 'Three-bracelet set strung in Nyamirambo.',
        vendor: 'Umuco Atelier',
        category: 'Fashion',
        categorySlug: 'fashion',
        status: 'ACTIVE',
        tags: ['beads', 'jewelry'],
        attributes: { material: 'Glass beads' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 9,
        variants: [{ sku: 'UA-BRC-3', title: 'Set of 3', model: 'Everyday', price: 8000, cost: 2500, stock: 35 }],
    },
    {
        storeSlug: 'cedar-wellness',
        name: 'Digital Thermometer',
        description: '60-second digital thermometer with a replaceable sleeve.',
        vendor: 'Cedar Wellness',
        category: 'Health',
        categorySlug: 'health',
        status: 'ACTIVE',
        tags: ['thermometer', 'clinic'],
        attributes: { form: 'Device', count: 1 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 21,
        variants: [{ sku: 'CW-THM-1', title: 'Standard', model: 'Home', price: 9000, cost: 4000, stock: 44 }],
    },
    {
        storeSlug: 'cedar-wellness',
        name: 'First Aid Pouch',
        description: 'Zip pouch with plasters, wipes, and a triangular bandage.',
        vendor: 'Cedar Wellness',
        category: 'Health',
        categorySlug: 'health',
        status: 'ACTIVE',
        tags: ['first-aid', 'kit'],
        attributes: { form: 'Kit', count: 18 },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 12,
        variants: [{ sku: 'CW-AID-18', title: '18 pieces', model: 'Travel', price: 13000, cost: 5600, stock: 23, attributes: { count: 18 } }],
    },
    {
        storeSlug: 'jollof-kitchen',
        name: 'Jollof Spice Kit',
        description: 'Measured spices for a pot that serves six.',
        vendor: 'Jollof Kitchen',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'ACTIVE',
        tags: ['spice', 'jollof'],
        attributes: { organic: false },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 16,
        variants: [
            { sku: 'JK-JOL-6', title: 'Serves 6', size: '6', model: 'Kit', price: 5500, cost: 2200, stock: 40, attributes: { weight: '120g' } },
            { sku: 'JK-JOL-12', title: 'Serves 12', size: '12', model: 'Kit', price: 9500, cost: 3900, stock: 18, attributes: { weight: '240g' } },
        ],
    },
    {
        storeSlug: 'jollof-kitchen',
        name: 'Smoked Pepper Mix',
        description: 'Coarse smoked pepper for stews and grilled fish.',
        vendor: 'Jollof Kitchen',
        category: 'Groceries',
        categorySlug: 'groceries',
        status: 'ACTIVE',
        tags: ['pepper', 'smoke'],
        attributes: { organic: true },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 8,
        variants: [{ sku: 'JK-PEP-80', title: '80g', size: '80g', model: 'Tin', price: 4500, cost: 1600, stock: 31, attributes: { weight: '80g' } }],
    },
    {
        storeSlug: 'acacia-living',
        name: 'Clay Table Vase',
        description: 'Unglazed clay vase thrown in Rulindo.',
        vendor: 'Acacia Living',
        category: 'Home',
        categorySlug: 'home',
        status: 'ACTIVE',
        tags: ['clay', 'vase'],
        attributes: { material: 'Clay', room: 'Dining' },
        deliveryPrice: 2500,
        deliveryLocation: 'City center',
        createdDaysAgo: 15,
        variants: [
            { sku: 'AL-VAS-S', title: 'Small', size: 'S', model: 'Bud', price: 14000, cost: 5500, stock: 16 },
            { sku: 'AL-VAS-M', title: 'Medium', size: 'M', model: 'Table', price: 21000, cost: 8600, stock: 9 },
        ],
    },
    {
        storeSlug: 'acacia-living',
        name: 'Handwoven Table Runner',
        description: 'Cotton runner with a charcoal stripe.',
        vendor: 'Acacia Living',
        category: 'Home',
        categorySlug: 'home',
        status: 'ACTIVE',
        tags: ['textile', 'table'],
        attributes: { material: 'Cotton', room: 'Dining' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 7,
        variants: [{ sku: 'AL-RUN-180', title: '180cm', size: '180cm', model: 'Stripe', price: 17000, cost: 7000, stock: 12 }],
    },
    {
        storeSlug: 'nile-sports',
        name: 'Adjustable Jump Rope',
        description: 'PVC rope with screw-lock handles.',
        vendor: 'Nile Sports',
        category: 'Sports',
        categorySlug: 'sports',
        status: 'ACTIVE',
        tags: ['cardio', 'rope'],
        attributes: { sport: 'Cardio', size: 'Adjustable' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 14,
        variants: [
            { sku: 'NS-ROP-BLK', title: 'Black', colorName: 'Black', colorHex: '#111111', model: 'Adjustable', price: 8000, cost: 3000, stock: 28 },
            { sku: 'NS-ROP-GRN', title: 'Field', colorName: 'Field', colorHex: '#16a34a', model: 'Adjustable', price: 8000, cost: 3000, stock: 16 },
        ],
    },
    {
        storeSlug: 'nile-sports',
        name: 'Yoga Block Pair',
        description: 'Two EVA blocks for floor work.',
        vendor: 'Nile Sports',
        category: 'Sports',
        categorySlug: 'sports',
        status: 'ACTIVE',
        tags: ['yoga', 'block'],
        attributes: { sport: 'Yoga', size: 'Pair' },
        deliveryPrice: 1500,
        deliveryLocation: 'City center',
        createdDaysAgo: 6,
        variants: [
            { sku: 'NS-BLK-PPL', title: 'Plum', colorName: 'Plum', colorHex: '#6b21a8', model: 'Pair', price: 11000, cost: 4200, stock: 14 },
            { sku: 'NS-BLK-SEA', title: 'Sea', colorName: 'Sea', colorHex: '#0e7490', model: 'Pair', price: 11000, cost: 4200, stock: 0 },
        ],
    },
]

export const EXTRA_PROMO_CODES: Array<{
    storeSlug: string | null
    code: string
    name: string
    type: 'PERCENT' | 'FIXED'
    value: number
    minOrderAmount?: number
    maxRedemptions?: number
    perUserLimit?: number
    productName?: string
    categorySlug?: string
}> = [
    { storeSlug: 'harvest-market', code: 'HONEY15', name: 'Honey 15% off', type: 'PERCENT', value: 15, minOrderAmount: 8000, maxRedemptions: 80, perUserLimit: 2, productName: 'Highland Honey' },
    { storeSlug: 'northline-electronics', code: 'GADGET5K', name: 'Gadgets 5000 off', type: 'FIXED', value: 5000, minOrderAmount: 20000, maxRedemptions: 40, perUserLimit: 1, productName: 'Harbor Bluetooth Speaker' },
    { storeSlug: 'atelier-threads', code: 'LINEN10', name: 'Linen 10% off', type: 'PERCENT', value: 10, minOrderAmount: 15000, maxRedemptions: 60, perUserLimit: 2, productName: 'Linen Shirt Dress' },
    { storeSlug: 'bloom-beauty', code: 'BLOOM20', name: 'Bloom welcome 20%', type: 'PERCENT', value: 20, minOrderAmount: 7000, maxRedemptions: 100, perUserLimit: 1 },
    { storeSlug: 'kigali-pantry', code: 'CHILI2', name: 'Chili oil 2000 off', type: 'FIXED', value: 2000, minOrderAmount: 4000, maxRedemptions: 50, perUserLimit: 3, productName: 'Akabanga Chili Oil' },
    { storeSlug: 'jollof-kitchen', code: 'POT10', name: 'Weekend pot 10%', type: 'PERCENT', value: 10, minOrderAmount: 5000, maxRedemptions: 70, perUserLimit: 2 },
    { storeSlug: 'umuco-atelier', code: 'TOTE500', name: 'Tote 500 off', type: 'FIXED', value: 500, minOrderAmount: 10000, maxRedemptions: 30, perUserLimit: 1, productName: 'Kitenge Tote Bag' },
    { storeSlug: null, code: 'HOME8', name: 'Home category 8% off', type: 'PERCENT', value: 8, minOrderAmount: 10000, maxRedemptions: 200, perUserLimit: 2, categorySlug: 'home' },
]
